(package "flycheck-dart"
         "0.1.0"
         "Flycheck for dart analyze")

(website-url "https://github.com/jcs090218/flycheck-dart")
(keywords "tools")

(package-file "flycheck-dart.el")

(script "test" "echo \"Error: no test specified\" && exit 1")

(source 'gnu)
(source 'melpa)

(depends-on "emacs" "26.1")
(depends-on "flycheck")
(depends-on "dart-mode")

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
